# Generated by Django 2.1.7 on 2019-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190217_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
