# Generated by Django 2.1.7 on 2019-02-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190218_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
